[tool.poetry]
name = "CAI"
version = "0.1.0"
description = ""
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "AGPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/yanyongyu/CAI"
repository = "https://github.com/yanyongyu/CAI"
documentation = "https://github.com/yanyongyu/CAI#readme"
keywords = ["qq", "mirai", "cqhttp"]
classifiers = ["Framework :: Robot Framework", "Programming Language :: Python :: 3"]
include = ["cai/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"
rtea = "^0.2.0"
jcestruct = "^0.1.0"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
